version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
    ports:
      - '1337:1337'
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: strapi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-strapi}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-strapi}
      POSTGRES_DB: ${POSTGRES_DB:-strapi}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db-data:
